---
title: "HW4"
author: "Corinna Hong"
date: "February 24, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center")
```

```{r}

# load packages

library(tidyverse)
library(janitor)
library(paletteer)

```

##1. Visualizing patterns of change for climate change data
```{r}

# read in and wrangle climate change data

climate_change <- read_csv("climate_change.csv") %>% 
  clean_names() %>% 
  mutate(geographic_range = str_to_lower(geographic_range))

```

```{r}

# Visualize changes in density due to development mode

climate_dev_bar <- ggplot(climate_change,
                          aes(x = species,
                              y = change_in_density,
                              fill = development_mode)) +
  geom_bar (stat = "identity") + # identity means height of bars equals actual value
   scale_fill_paletteer_d("ghibli::MononokeMedium", direction = -1) + # direction -1 means start from the right side of the palette
  theme_minimal()

climate_dev_bar



# Visualize changes in density due to geographic range

climate_geo_bar <- ggplot(climate_change,
                          aes(x = species,
                              y = change_in_density,
                              fill = geographic_range)) +
  geom_bar(stat = "identity") +
  scale_fill_paletteer_d("ghibli::MononokeMedium", direction = -1) +
  theme_minimal()

climate_geo_bar # PATTERN: Southern species increase, Northern species decreased.



# Visualize changes in density due to trophic level

climate_tro_bar <- ggplot(climate_change,
                          aes(x = species,
                              y = change_in_density,
                              fill = trophic_level)) +
  geom_bar(stat = "identity") +
  scale_fill_paletteer_d("ghibli::MononokeMedium", direction = -1) +
  theme_minimal()

climate_tro_bar


```

## 2. Visualizing changes at nuclear power plant
```{r}

# Read in and wrangle data for nuclear power plant

nuclear_power <- read_csv("nuclear_power.csv") %>% 
  clean_names() %>% 
  gather(`hyperion_bay`,`noway_bay`,`diablo_cove`, key = "site", value = "density") # Density measured in (# of individuals/100m2)

```

```{r}

# Visualize change in all species across all sites

nuclear_species <- ggplot(nuclear_power, aes(x = year, y = density, fill = site)) +
  geom_line(aes(color = site)) +
  scale_color_paletteer_d("ghibli::MononokeMedium", direction = -1) +
  facet_wrap(~species, scale = "free", nrow = 3) +
  theme_minimal()

nuclear_species

```

```{r}

# Read in and wrangle data for crab fishery

crab_barnacle <- read_csv("crab_barnacle.csv") %>% 
  clean_names() %>% 
  gather(`cancer_ca`,`cancer_or`,`barnacle_ca`,`barnacle_or`, key = "site", value = "density") %>% 
  spread(stage, density) %>% 
  rename(adult_density = Adult) %>% # rename column
  rename(recruit_density = Recruit) %>% 
  separate(site, into = c("species", "site"), sep = "_") %>%  # separate species from site
  arrange(year, species)

```

```{r}

# Read in and wrangle data for upwelling indices

upwelling <- read_csv("upwelling.csv") %>% 
  clean_names() %>% 
  gather(`winter_ca`,`summer_ca`,`winter_or`,`summer_or`, key = "season", value = "upwelling_indices") %>% # gather seasons & put values in a separate col
  separate(season, into = c("season","site"), sep = "_") %>% 
  arrange(year)

```

```{r}

# Join crab_barnacle to upwelling

crab_fishery <- left_join(crab_barnacle, upwelling) %>% # join two dataframes, default wwill join by matching columns in this case, "year" and "site"
  clean_names() %>% 
  arrange(year)

# crab_fishery$year <- as.character(crab_fishery$year) 

```

## 3. Visualizing patterns of change for crab fishery
```{r}

# Relationship betewwen density of adult and next year's recruits for barnacles

adult_barnacles <- crab_fishery %>% 
  filter(species == "barnacle")

adult_barnacles_plot <- ggplot(adult_barnacles, aes(x = adult_density, y = recruit_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_wrap(~site, scale = "free") +
  theme_classic()

adult_barnacles_plot




# Relationship between density of adult and next year's recruits in crabs

adult_crabs <- crab_fishery %>% 
  filter(species == "cancer")

adult_crabs_plot <- ggplot(adult_crabs, aes(x = adult_density, y = recruit_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_wrap(~site, scale = "free") +
  theme_classic()

adult_crabs_plot


```

```{r}

# Relationship between desnsity of recruits and upwelling indicies for barnacles

barnacle_up_recruit_plot <- ggplot(adult_barnacles, aes(x = upwelling_indices, y = recruit_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_grid(site ~ season, scale = "free") +
  theme_bw()

barnacle_up_recruit_plot



# Relationship between density of adults and upwelling indicies for barnacles


barnacle_up_adult_plot <- ggplot(adult_barnacles, aes(x = upwelling_indices, y = adult_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_grid(site ~ season, scale = "free") +
  theme_bw()

barnacle_up_adult_plot



# Relationship between density of recruits and upwelling indicies for crabs

crab_up_recruit_plot <- ggplot(adult_crabs, aes(x = upwelling_indices, y = recruit_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_grid(site ~ season, scale = "free") +
  theme_bw()

crab_up_recruit_plot



# Relationship between density of adults and upwelling indicies for crabs

crab_up_adult_plot <- ggplot(adult_crabs, aes(x = upwelling_indices, y = adult_density)) +
  geom_point(aes(color = year)) +
  scale_color_paletteer_c("gameofthrones::lannister", direction = -1) +
  facet_grid(site ~ season, scale = "free") +
  theme_bw()

crab_up_adult_plot

```

